---
settings:
  parallel: true

driver:
  name: vagrant

provisioner:
  name: chef_zero
  # https://github.com/chef/chef/issues/5362
  chef_omnibus_install_options: -c current
  # our tmp.mount test unit masks default /tmp path on ubuntu
  root_path: /var/tmp/kitchen

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: fedora-24
    run_list:
      - recipe[yum::dnf_yum_compat]
  - name: debian-8.5
    run_list:
      - recipe[debian::backports]
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      systemd:
        hostname: my-hostname.example.come
